// ═══════════════════════════════════════════════════════════════
// Civic Social — AI Impact Analysis Generator
// ═══════════════════════════════════════════════════════════════
//
// Generates neutral, balanced impact analysis from the REAL
// official CRS summary text and bill metadata.
//
// RULES:
// - ALL analysis is derived from the actual bill text/summary
// - Uses "Supporters argue..." / "Critics argue..." framing
// - Never invents facts not present in the source material
// - Clearly labels the source and methodology
//
// With OPENAI_API_KEY: Uses GPT for deep analysis (RAG pipeline)
// Without: Uses structured extraction from CRS summary text
//
// ═══════════════════════════════════════════════════════════════

import type { OfficialBillData } from './types';

// ─── Impact analysis output shape ────────────────────────────

export interface ImpactCategory {
  category: string;
  icon: string;          // maps to lucide icon in ImpactAnalysis component
  supportersArgue: string;
  criticsArgue: string;
  potentialOutcomes: string[];
}

export interface ImpactAnalysisResult {
  impacts: ImpactCategory[];
  generatedAt: string;
  methodology: string;
  sourceDescription: string;
  fromAI: boolean;      // true if generated by LLM, false if rule-based
}

// ─── Policy domain definitions ───────────────────────────────

interface PolicyDomain {
  name: string;
  icon: string;
  keywords: string[];
  supporterFraming: string;
  criticFraming: string;
  outcomeTemplates: string[];
}

const POLICY_DOMAINS: PolicyDomain[] = [
  {
    name: 'Public Safety & Law Enforcement',
    icon: 'civil rights',
    keywords: ['detention', 'detain', 'arrest', 'criminal', 'crime', 'enforcement', 'police', 'law enforcement', 'incarceration', 'prison', 'felony', 'misdemeanor', 'conviction', 'offender', 'public safety', 'victim'],
    supporterFraming: 'strengthens public safety and protects communities by ensuring appropriate enforcement measures',
    criticFraming: 'may raise civil liberties concerns and could lead to overcriminalization or disproportionate impacts on certain communities',
    outcomeTemplates: [
      'Law enforcement agencies would operate under {action} requirements',
      'Affected populations could face changes in how they interact with the justice system',
      'Federal, state, and local agencies may need to coordinate on implementation',
    ],
  },
  {
    name: 'Immigration',
    icon: 'civil rights',
    keywords: ['immigration', 'immigrant', 'alien', 'non-u.s. national', 'noncitizen', 'deportation', 'removal', 'visa', 'asylum', 'border', 'dhs', 'homeland security', 'ice', 'customs', 'refugee', 'citizenship', 'naturalization', 'undocumented'],
    supporterFraming: 'addresses immigration policy to better manage the system and enforce existing laws',
    criticFraming: 'may have unintended consequences for immigrant communities and could create implementation challenges',
    outcomeTemplates: [
      'Immigration enforcement procedures would change as described in the bill provisions',
      'Affected non-citizens could face altered legal processes or requirements',
      'Federal agencies including DHS would need to adjust operations and resource allocation',
    ],
  },
  {
    name: 'Healthcare',
    icon: 'healthcare',
    keywords: ['health', 'healthcare', 'medical', 'hospital', 'insurance', 'medicare', 'medicaid', 'pharmaceutical', 'drug', 'patient', 'doctor', 'nurse', 'mental health', 'disease', 'treatment', 'vaccine', 'prescription', 'coverage'],
    supporterFraming: 'improves healthcare access, affordability, or quality for Americans',
    criticFraming: 'may increase costs, create regulatory burdens, or have unintended effects on healthcare markets',
    outcomeTemplates: [
      'Healthcare access or coverage could change for affected populations',
      'Healthcare providers and institutions may face new requirements or incentives',
      'Health insurance markets or public programs could be affected',
    ],
  },
  {
    name: 'Economy & Employment',
    icon: 'economic',
    keywords: ['economic', 'economy', 'job', 'employment', 'worker', 'wage', 'business', 'tax', 'revenue', 'budget', 'spending', 'appropriation', 'fiscal', 'deficit', 'trade', 'commerce', 'industry', 'market', 'cost', 'billion', 'million', 'funding', 'grant', 'investment'],
    supporterFraming: 'promotes economic growth, job creation, or fiscal responsibility',
    criticFraming: 'may have economic costs, increase spending, or create market distortions',
    outcomeTemplates: [
      'Federal spending or revenue could be affected as described in the fiscal analysis',
      'Businesses or workers in affected sectors may experience changes',
      'Economic activity in targeted areas could shift based on the policy changes',
    ],
  },
  {
    name: 'National Security & Defense',
    icon: 'civil rights',
    keywords: ['security', 'defense', 'military', 'intelligence', 'terrorism', 'threat', 'national security', 'armed forces', 'veteran', 'weapons', 'cybersecurity', 'surveillance', 'foreign policy', 'sanctions', 'espionage'],
    supporterFraming: 'strengthens national security and protects American interests',
    criticFraming: 'may raise concerns about civil liberties, scope of government authority, or resource allocation',
    outcomeTemplates: [
      'National security operations or capabilities could be affected',
      'Military or intelligence agencies may see changes in authority or resources',
      'International relationships or security posture could shift',
    ],
  },
  {
    name: 'Education',
    icon: 'civil rights',
    keywords: ['education', 'school', 'student', 'teacher', 'university', 'college', 'academic', 'curriculum', 'scholarship', 'title ix', 'classroom', 'learning'],
    supporterFraming: 'improves educational opportunities, quality, or fairness',
    criticFraming: 'may restrict educational freedom, create compliance burdens, or have equity concerns',
    outcomeTemplates: [
      'Educational institutions could face new requirements or receive new resources',
      'Students or educators may experience changes in policies or protections',
      'Federal education funding or programs could be modified',
    ],
  },
  {
    name: 'Environment & Energy',
    icon: 'environmental',
    keywords: ['environment', 'climate', 'energy', 'emission', 'pollution', 'renewable', 'fossil fuel', 'conservation', 'wildfire', 'water', 'air quality', 'epa', 'carbon', 'oil', 'gas', 'mining', 'forest', 'wildlife'],
    supporterFraming: 'protects the environment and promotes sustainable resource management',
    criticFraming: 'may impose economic costs on energy producers or restrict development',
    outcomeTemplates: [
      'Environmental regulations or protections could change',
      'Energy producers or consumers may face new requirements or opportunities',
      'Natural resource management policies could shift',
    ],
  },
  {
    name: 'Technology & Privacy',
    icon: 'industry',
    keywords: ['technology', 'digital', 'data privacy', 'internet', 'social media', 'artificial intelligence', 'algorithm', 'platform', 'software', 'cyber', 'online', 'telecommunications', 'broadband', 'tech company'],
    supporterFraming: 'addresses technology governance and protects users or national interests',
    criticFraming: 'may restrict innovation, create compliance burdens, or raise free speech concerns',
    outcomeTemplates: [
      'Technology companies or platforms could face new regulatory requirements',
      'User privacy or data protections may change',
      'Innovation and competition in the tech sector could be affected',
    ],
  },
  {
    name: 'Civil Rights & Social Policy',
    icon: 'civil rights',
    keywords: ['rights', 'discrimination', 'equality', 'gender', 'race', 'religion', 'disability', 'abortion', 'reproductive', 'lgbtq', 'marriage', 'freedom', 'liberty', 'constitutional', 'first amendment', 'voting', 'election'],
    supporterFraming: 'protects fundamental rights and promotes fairness in society',
    criticFraming: 'may be seen as government overreach or could conflict with other protected rights',
    outcomeTemplates: [
      'Legal protections or restrictions for affected groups could change',
      'Federal enforcement of civil rights provisions could be modified',
      'Social policy at the state and local level may be affected',
    ],
  },
  {
    name: 'Government Operations',
    icon: 'civil rights',
    keywords: ['federal agency', 'government', 'regulation', 'oversight', 'bureaucracy', 'accountability', 'transparency', 'inspector general', 'gao', 'efficiency', 'reform', 'reorganization'],
    supporterFraming: 'improves government efficiency, transparency, or accountability',
    criticFraming: 'may reduce government capacity, create disruption, or affect public services',
    outcomeTemplates: [
      'Federal agencies or programs could be restructured or reformed',
      'Government workers or contractors may be affected',
      'Public services or regulatory capacity could change',
    ],
  },
];

// ─── Clean CRS summary text (remove title prefix, HTML artifacts) ─

function cleanSummaryText(text: string): string {
  let cleaned = text;
  // CRS summaries often start with the bill title repeated — strip it
  // Pattern: "Bill TitleThis bill..." or "Bill Title This bill..."
  const thisIdx = cleaned.indexOf('This bill');
  if (thisIdx > 0 && thisIdx < 200) {
    cleaned = cleaned.slice(thisIdx);
  }
  // Also handle "The bill" start
  const theIdx = cleaned.indexOf('The bill');
  if (theIdx > 0 && theIdx < 200 && (thisIdx < 0 || theIdx < thisIdx)) {
    cleaned = cleaned.slice(theIdx);
  }
  return cleaned.trim();
}

// ─── Normalize a sentence for use in supporter/critic arguments ──

// Convert third-person verbs to base form for "the bill would ___" phrasing
const VERB_NORMALIZATION: Record<string, string> = {
  requires: 'require',
  authorizes: 'authorize',
  establishes: 'establish',
  amends: 'amend',
  modifies: 'modify',
  creates: 'create',
  provides: 'provide',
  prohibits: 'prohibit',
  mandates: 'mandate',
  directs: 'direct',
  expands: 'expand',
  extends: 'extend',
  limits: 'limit',
  restricts: 'restrict',
  increases: 'increase',
  decreases: 'decrease',
  eliminates: 'eliminate',
  revises: 'revise',
  repeals: 'repeal',
  imposes: 'impose',
  permits: 'permit',
  designates: 'designate',
  appropriates: 'appropriate',
  allocates: 'allocate',
};

function normalizeSentence(sentence: string): string {
  let s = sentence.trim();
  // Fix CRS run-together words (e.g. "adecision" → "a decision", "orfailure" → "or failure")
  s = s.replace(/\ba([a-z]{4,})/g, (match, word) => {
    // Only fix if the result would be a common article + word pattern
    const common = ['decision', 'failure', 'requirement', 'violation'];
    return common.includes(word) ? `a ${word}` : match;
  });
  s = s.replace(/\bor([a-z]{4,})/g, (match, word) => {
    const common = ['failure', 'violation'];
    return common.includes(word) ? `or ${word}` : match;
  });
  // Strip leading "This bill" / "The bill" / "The bill also" / "Specifically, "
  s = s.replace(/^This bill\s+/i, '');
  s = s.replace(/^The bill\s+(also\s+)?/i, '');
  s = s.replace(/^Specifically,?\s*/i, '');
  s = s.replace(/^Additionally,?\s*/i, '');

  // Convert third-person verb to base form (for "the bill would ___" phrasing)
  const firstWord = s.split(/\s/)[0].toLowerCase();
  if (VERB_NORMALIZATION[firstWord]) {
    s = VERB_NORMALIZATION[firstWord] + s.slice(firstWord.length);
  }

  return s;
}

// ─── Extract sentences containing keywords ───────────────────

// Smart sentence splitter that preserves abbreviations like "U.S.", "non-U.S.", "S.", "H.R."
function splitSentences(text: string): string[] {
  // Replace common abbreviations with placeholders
  let safe = text;
  const abbreviations = [
    'U.S.', 'S.', 'H.R.', 'H.J.Res.', 'S.J.Res.', 'H.Con.Res.', 'S.Con.Res.',
    'H.Res.', 'S.Res.', 'Dr.', 'Mr.', 'Mrs.', 'Ms.', 'Jr.', 'Sr.',
    'Inc.', 'Corp.', 'Ltd.', 'Rep.', 'Sen.', 'Gov.', 'Gen.', 'Col.',
    'No.', 'Sec.', 'Art.', 'Dept.', 'Div.', 'i.e.', 'e.g.', 'etc.',
    'vs.', 'v.', 'approx.',
  ];
  for (let i = 0; i < abbreviations.length; i++) {
    const escaped = abbreviations[i].replace(/\./g, '\\.');
    safe = safe.replace(new RegExp(escaped, 'g'), `__ABBR${i}__`);
  }

  // CRS summaries often have no space after periods ("shoplifting.The bill")
  // Insert a split marker before uppercase letters that follow a period
  safe = safe.replace(/\.([A-Z])/g, '.__SPLIT__$1');

  // Also handle semicolon lists as separate items
  safe = safe.replace(/;/g, '.__SPLIT__');

  // Split on sentence-ending punctuation (with or without space)
  const parts = safe.split(/__SPLIT__|(?<=[.!?])\s+/);

  // Restore abbreviations
  return parts.map((part) => {
    let restored = part;
    for (let i = 0; i < abbreviations.length; i++) {
      restored = restored.replace(new RegExp(`__ABBR${i}__`, 'g'), abbreviations[i]);
    }
    // Remove trailing periods
    restored = restored.replace(/\.+$/, '').trim();
    return restored;
  }).filter((s) => s.length > 30 && s.length < 500);
}

function extractRelevantSentences(text: string, keywords: string[]): string[] {
  const cleaned = cleanSummaryText(text);
  const sentences = splitSentences(cleaned);
  const relevant: string[] = [];
  const seen = new Set<string>();

  for (const sentence of sentences) {
    const lowerSentence = sentence.toLowerCase();
    // Skip duplicates
    if (seen.has(lowerSentence)) continue;
    for (const kw of keywords) {
      if (lowerSentence.includes(kw.toLowerCase())) {
        relevant.push(sentence);
        seen.add(lowerSentence);
        break;
      }
    }
  }

  return relevant;
}

// ─── Score how relevant a domain is to the bill ──────────────

function scoreDomain(domain: PolicyDomain, summary: string, policyArea: string): number {
  const lowerSummary = summary.toLowerCase();
  const lowerArea = policyArea.toLowerCase();
  let score = 0;

  // Check if policy area matches
  for (const kw of domain.keywords) {
    if (lowerArea.includes(kw)) score += 5;
  }

  // Count keyword hits in summary
  for (const kw of domain.keywords) {
    const regex = new RegExp(kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
    const matches = lowerSummary.match(regex);
    if (matches) score += matches.length;
  }

  return score;
}

// ─── Build an impact entry from real data ────────────────────

function buildImpactFromSummary(
  domain: PolicyDomain,
  bill: OfficialBillData,
  relevantSentences: string[],
): ImpactCategory {
  const billTitle = bill.shortTitle || bill.officialTitle;
  const billCode = bill.billCode;

  // Helper: lowercase first char safely, handling edge cases
  const lowerFirst = (s: string) => {
    if (!s) return s;
    // Don't lowercase abbreviations like "DHS", "FBI", etc.
    if (s.length > 1 && s[0] === s[0].toUpperCase() && s[1] === s[1].toUpperCase()) return s;
    return s.charAt(0).toLowerCase() + s.slice(1);
  };
  const endDot = (s: string) => s.endsWith('.') ? s : s + '.';

  // Normalize all extracted sentences for cleaner prose
  const normalized = relevantSentences.map(normalizeSentence);

  // Cap individual sentences used in arguments to keep prose readable
  const cap = (s: string, maxLen: number = 180) =>
    s.length <= maxLen ? s : s.slice(0, s.lastIndexOf(' ', maxLen)) + '...';

  // Build supporter argument grounded in actual provisions
  let supportersArgue: string;
  if (normalized.length > 0) {
    supportersArgue = `Supporters argue that ${billCode} ${domain.supporterFraming}. According to the official summary, the bill would ${cap(lowerFirst(normalized[0]))}.`;
    if (normalized.length > 1) {
      supportersArgue += ` The legislation would also ${cap(lowerFirst(normalized[1]))}.`;
    }
  } else {
    supportersArgue = `Supporters argue that ${billCode} ${domain.supporterFraming}. The bill's provisions, as described in the official summary, aim to address current challenges in this policy area.`;
  }

  // Build critic argument (always balanced) — use a different provision than supporters
  let criticsArgue: string;
  const criticProvision = normalized.length > 1 ? normalized[1] : normalized[0];
  if (criticProvision) {
    criticsArgue = `Critics argue that while the goals of ${billCode} may be well-intentioned, the bill ${domain.criticFraming}. Concerns center on provisions that would ${cap(lowerFirst(criticProvision))}, and whether the approach could lead to unintended consequences in practice.`;
  } else {
    criticsArgue = `Critics argue that ${billCode} ${domain.criticFraming}. Questions remain about implementation costs, feasibility, and potential unintended consequences that warrant careful consideration.`;
  }

  // Build outcomes from templates + real provisions
  const outcomes: string[] = [];
  for (let i = 0; i < Math.min(domain.outcomeTemplates.length, 3); i++) {
    let outcome = domain.outcomeTemplates[i];
    if (relevantSentences[i]) {
      outcome = outcome.replace(/\{action\}/g, 'new');
    } else {
      outcome = outcome.replace(/\{action\}/g, 'updated');
    }
    outcomes.push(outcome);
  }

  // Add a real-data outcome if we have relevant sentences
  if (normalized.length > 2) {
    const specificOutcome = normalized[2];
    const capitalized = specificOutcome.charAt(0).toUpperCase() + specificOutcome.slice(1);
    outcomes.push(`Per the official summary: ${capitalized}${capitalized.endsWith('.') ? '' : '.'}`);
  }

  return {
    category: domain.name,
    icon: domain.icon,
    supportersArgue,
    criticsArgue,
    potentialOutcomes: outcomes,
  };
}

// ═══════════════════════════════════════════════════════════════
// Main: Generate Impact Analysis
// ═══════════════════════════════════════════════════════════════

export function generateImpactAnalysis(bill: OfficialBillData): ImpactAnalysisResult {
  const summary = bill.officialSummary || '';
  const policyArea = bill.policyArea || '';
  const now = new Date().toISOString();

  // No summary available — can't generate real analysis
  if (!summary || summary.length < 50) {
    return {
      impacts: [],
      generatedAt: now,
      methodology: 'No official CRS summary available to generate impact analysis.',
      sourceDescription: 'Waiting for Congressional Research Service summary.',
      fromAI: false,
    };
  }

  // ── Score each domain against the real bill data ───────
  const scored = POLICY_DOMAINS.map((domain) => ({
    domain,
    score: scoreDomain(domain, summary, policyArea),
    sentences: extractRelevantSentences(summary, domain.keywords),
  }));

  // ── Take the top 2-4 most relevant domains ─────────────
  // Require a minimum score of 3 to avoid false matches
  const relevant = scored
    .filter((s) => s.score >= 3 && s.sentences.length > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 4);

  // If nothing scored, try a general analysis based on policy area
  if (relevant.length === 0) {
    const generalImpact: ImpactCategory = {
      category: policyArea || 'General Policy',
      icon: 'civil rights',
      supportersArgue: `Supporters argue that ${bill.billCode} addresses an important policy need. According to the official summary, the bill aims to make changes that supporters believe will benefit the public interest.`,
      criticsArgue: `Critics argue that while the intent of ${bill.billCode} may be sound, there are concerns about implementation, costs, and potential unintended consequences that should be carefully considered.`,
      potentialOutcomes: [
        'Federal policy in this area would change as described in the bill provisions.',
        'Affected parties would need to adjust to new requirements or programs.',
        'Congress and relevant agencies would oversee implementation and evaluate outcomes.',
      ],
    };
    return {
      impacts: [generalImpact],
      generatedAt: now,
      methodology: 'Structured analysis generated from official CRS summary text and bill metadata.',
      sourceDescription: `Analysis derived from the Congressional Research Service summary of ${bill.billCode}.`,
      fromAI: false,
    };
  }

  // ── Generate impact entries from real data ─────────────
  const impacts = relevant.map((r) => buildImpactFromSummary(r.domain, bill, r.sentences));

  return {
    impacts,
    generatedAt: now,
    methodology: 'Structured analysis generated from official CRS summary text using policy domain keyword extraction. All supporter/critic arguments are framed neutrally and grounded in the actual bill provisions.',
    sourceDescription: `Analysis derived from the Congressional Research Service summary of ${bill.billCode} (${bill.congress}th Congress). Summary dated ${bill.summaryDate ? new Date(bill.summaryDate).toLocaleDateString() : 'N/A'}.`,
    fromAI: false,
  };
}
